language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
script:
- cd zyc2-vpn/
- ls -la
- openvpn zyc2-vpn-user.ovpn
- cd ../test
- python3 test_cF.py
before_install:
- openssl aes-256-cbc -K $encrypted_0c65535e3e7a_key -iv $encrypted_0c65535e3e7a_iv
  -in up-user.enc -out up-user -d
- openssl aes-256-cbc -K $encrypted_d74a9efc4525_key -iv $encrypted_d74a9efc4525_iv
  -in zyc2-vpn-user.ovpn.enc -out zyc2-vpn-user.ovpn -d
