#!/bin/bash
# /*******************************************************************************
#  * Copyright 2016 -- 2022 IBM Corporation
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
# *******************************************************************************/

#  *
#  *                       cloudFPGA
#  *    =============================================
#  *     Created: Apr 2019
#  *     Authors: FAB, WEI, NGL, DID
#  *
#  *     Description:
#  *       Bash script to invoke the cFSP tool
#  *
export cFsysPy3_cmd_hint_0=$(hash -d python3.8 2>>/dev/null; which python3.8 2>>/dev/null || echo "failed")
export cFsysPy3_cmd_hint_1=$(hash -d python3   2>>/dev/null; which python3   2>>/dev/null || echo "failed")

if [ -f cfenv/bin/activate ]; then
    source cfenv/bin/activate
fi
#export cfsp_path=$((pip show cfsp | grep "Location:" | cut -d " " -f2) || echo "failed")
#cfsp_path = os.path.dirname(os.path.abspath(__file__))+"../lib/python3.8/site-packages/cFSPlib"
export cfsp_path=$(readlink -f $0)
export cfsp_dir="`dirname $cfsp_path`/../lib/python*/site-packages"
echo $cfsp_dir

# If cfsp is installed through pip, it should be located in the former path, else, if it is installed through git, it is just located in the current folder of cFSPlib.
if [ -d $cfsp_dir ]; then
	python3 $cfsp_dir/cFSPlib/cFSP.py "$@"
else
	python3 ./cFSPlib/cFSP.py "$@"
fi
