# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BuildScript(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'hash': 'str',
        'hash_algorithm': 'str',
        'name': 'str',
        'version': 'str'
    }

    attribute_map = {
        'comment': 'comment',
        'hash': 'hash',
        'hash_algorithm': 'hash_algorithm',
        'name': 'name',
        'version': 'version'
    }

    def __init__(self, comment=None, hash=None, hash_algorithm=None, name=None, version=None):  # noqa: E501
        """BuildScript - a model defined in Swagger"""  # noqa: E501
        self._comment = None
        self._hash = None
        self._hash_algorithm = None
        self._name = None
        self._version = None
        self.discriminator = None
        if comment is not None:
            self.comment = comment
        if hash is not None:
            self.hash = hash
        if hash_algorithm is not None:
            self.hash_algorithm = hash_algorithm
        if name is not None:
            self.name = name
        if version is not None:
            self.version = version

    @property
    def comment(self):
        """Gets the comment of this BuildScript.  # noqa: E501

        Some valuable information for humans  # noqa: E501

        :return: The comment of this BuildScript.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this BuildScript.

        Some valuable information for humans  # noqa: E501

        :param comment: The comment of this BuildScript.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def hash(self):
        """Gets the hash of this BuildScript.  # noqa: E501

        Hash of the build script to register  # noqa: E501

        :return: The hash of this BuildScript.  # noqa: E501
        :rtype: str
        """
        return self._hash

    @hash.setter
    def hash(self, hash):
        """Sets the hash of this BuildScript.

        Hash of the build script to register  # noqa: E501

        :param hash: The hash of this BuildScript.  # noqa: E501
        :type: str
        """

        self._hash = hash

    @property
    def hash_algorithm(self):
        """Gets the hash_algorithm of this BuildScript.  # noqa: E501

        Algorithm used to create the hash  # noqa: E501

        :return: The hash_algorithm of this BuildScript.  # noqa: E501
        :rtype: str
        """
        return self._hash_algorithm

    @hash_algorithm.setter
    def hash_algorithm(self, hash_algorithm):
        """Sets the hash_algorithm of this BuildScript.

        Algorithm used to create the hash  # noqa: E501

        :param hash_algorithm: The hash_algorithm of this BuildScript.  # noqa: E501
        :type: str
        """

        self._hash_algorithm = hash_algorithm

    @property
    def name(self):
        """Gets the name of this BuildScript.  # noqa: E501

        Name of the build script  # noqa: E501

        :return: The name of this BuildScript.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BuildScript.

        Name of the build script  # noqa: E501

        :param name: The name of this BuildScript.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def version(self):
        """Gets the version of this BuildScript.  # noqa: E501

        Version of the build script  # noqa: E501

        :return: The version of this BuildScript.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this BuildScript.

        Version of the build script  # noqa: E501

        :param version: The version of this BuildScript.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BuildScript, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuildScript):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
