# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2002(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'by_inst_id': 'dict(str, object)',
        'by_rank': 'dict(str, object)'
    }

    attribute_map = {
        'by_inst_id': 'by_inst_id',
        'by_rank': 'by_rank'
    }

    def __init__(self, by_inst_id=None, by_rank=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger"""  # noqa: E501
        self._by_inst_id = None
        self._by_rank = None
        self.discriminator = None
        if by_inst_id is not None:
            self.by_inst_id = by_inst_id
        if by_rank is not None:
            self.by_rank = by_rank

    @property
    def by_inst_id(self):
        """Gets the by_inst_id of this InlineResponse2002.  # noqa: E501


        :return: The by_inst_id of this InlineResponse2002.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._by_inst_id

    @by_inst_id.setter
    def by_inst_id(self, by_inst_id):
        """Sets the by_inst_id of this InlineResponse2002.


        :param by_inst_id: The by_inst_id of this InlineResponse2002.  # noqa: E501
        :type: dict(str, object)
        """

        self._by_inst_id = by_inst_id

    @property
    def by_rank(self):
        """Gets the by_rank of this InlineResponse2002.  # noqa: E501


        :return: The by_rank of this InlineResponse2002.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._by_rank

    @by_rank.setter
    def by_rank(self, by_rank):
        """Sets the by_rank of this InlineResponse2002.


        :param by_rank: The by_rank of this InlineResponse2002.  # noqa: E501
        :type: dict(str, object)
        """

        self._by_rank = by_rank

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2002, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
