# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InstanceIdApiGatewayBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'custom_request_method': 'str',
        'custom_request_uri': 'str',
        'custom_request_payload': 'str'
    }

    attribute_map = {
        'custom_request_method': 'custom_request_method',
        'custom_request_uri': 'custom_request_uri',
        'custom_request_payload': 'custom_request_payload'
    }

    def __init__(self, custom_request_method=None, custom_request_uri=None, custom_request_payload=None):  # noqa: E501
        """InstanceIdApiGatewayBody - a model defined in Swagger"""  # noqa: E501
        self._custom_request_method = None
        self._custom_request_uri = None
        self._custom_request_payload = None
        self.discriminator = None
        self.custom_request_method = custom_request_method
        self.custom_request_uri = custom_request_uri
        if custom_request_payload is not None:
            self.custom_request_payload = custom_request_payload

    @property
    def custom_request_method(self):
        """Gets the custom_request_method of this InstanceIdApiGatewayBody.  # noqa: E501

        The METHOD of the custom API request  # noqa: E501

        :return: The custom_request_method of this InstanceIdApiGatewayBody.  # noqa: E501
        :rtype: str
        """
        return self._custom_request_method

    @custom_request_method.setter
    def custom_request_method(self, custom_request_method):
        """Sets the custom_request_method of this InstanceIdApiGatewayBody.

        The METHOD of the custom API request  # noqa: E501

        :param custom_request_method: The custom_request_method of this InstanceIdApiGatewayBody.  # noqa: E501
        :type: str
        """
        if custom_request_method is None:
            raise ValueError("Invalid value for `custom_request_method`, must not be `None`")  # noqa: E501

        self._custom_request_method = custom_request_method

    @property
    def custom_request_uri(self):
        """Gets the custom_request_uri of this InstanceIdApiGatewayBody.  # noqa: E501

        The URI (i.e. path) of the custom API request  # noqa: E501

        :return: The custom_request_uri of this InstanceIdApiGatewayBody.  # noqa: E501
        :rtype: str
        """
        return self._custom_request_uri

    @custom_request_uri.setter
    def custom_request_uri(self, custom_request_uri):
        """Sets the custom_request_uri of this InstanceIdApiGatewayBody.

        The URI (i.e. path) of the custom API request  # noqa: E501

        :param custom_request_uri: The custom_request_uri of this InstanceIdApiGatewayBody.  # noqa: E501
        :type: str
        """
        if custom_request_uri is None:
            raise ValueError("Invalid value for `custom_request_uri`, must not be `None`")  # noqa: E501

        self._custom_request_uri = custom_request_uri

    @property
    def custom_request_payload(self):
        """Gets the custom_request_payload of this InstanceIdApiGatewayBody.  # noqa: E501

        The PAYLPOAD (i.e. body) of the custom API request  # noqa: E501

        :return: The custom_request_payload of this InstanceIdApiGatewayBody.  # noqa: E501
        :rtype: str
        """
        return self._custom_request_payload

    @custom_request_payload.setter
    def custom_request_payload(self, custom_request_payload):
        """Sets the custom_request_payload of this InstanceIdApiGatewayBody.

        The PAYLPOAD (i.e. body) of the custom API request  # noqa: E501

        :param custom_request_payload: The custom_request_payload of this InstanceIdApiGatewayBody.  # noqa: E501
        :type: str
        """

        self._custom_request_payload = custom_request_payload

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InstanceIdApiGatewayBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstanceIdApiGatewayBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
