# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InstanceIdRunlevelBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'new_runlevel': 'int'
    }

    attribute_map = {
        'new_runlevel': 'new_runlevel'
    }

    def __init__(self, new_runlevel=None):  # noqa: E501
        """InstanceIdRunlevelBody - a model defined in Swagger"""  # noqa: E501
        self._new_runlevel = None
        self.discriminator = None
        self.new_runlevel = new_runlevel

    @property
    def new_runlevel(self):
        """Gets the new_runlevel of this InstanceIdRunlevelBody.  # noqa: E501


        :return: The new_runlevel of this InstanceIdRunlevelBody.  # noqa: E501
        :rtype: int
        """
        return self._new_runlevel

    @new_runlevel.setter
    def new_runlevel(self, new_runlevel):
        """Sets the new_runlevel of this InstanceIdRunlevelBody.


        :param new_runlevel: The new_runlevel of this InstanceIdRunlevelBody.  # noqa: E501
        :type: int
        """
        if new_runlevel is None:
            raise ValueError("Invalid value for `new_runlevel`, must not be `None`")  # noqa: E501

        self._new_runlevel = new_runlevel

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InstanceIdRunlevelBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstanceIdRunlevelBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
