# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NodeMapInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'image_id': 'str',
        'instance_id': 'int',
        'node_id': 'int',
        'node_ip': 'str'
    }

    attribute_map = {
        'image_id': 'image_id',
        'instance_id': 'instance_id',
        'node_id': 'node_id',
        'node_ip': 'node_ip'
    }

    def __init__(self, image_id=None, instance_id=None, node_id=None, node_ip=None):  # noqa: E501
        """NodeMapInner - a model defined in Swagger"""  # noqa: E501
        self._image_id = None
        self._instance_id = None
        self._node_id = None
        self._node_ip = None
        self.discriminator = None
        if image_id is not None:
            self.image_id = image_id
        if instance_id is not None:
            self.instance_id = instance_id
        if node_id is not None:
            self.node_id = node_id
        if node_ip is not None:
            self.node_ip = node_ip

    @property
    def image_id(self):
        """Gets the image_id of this NodeMapInner.  # noqa: E501

        ID of Image for that Node  # noqa: E501

        :return: The image_id of this NodeMapInner.  # noqa: E501
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id):
        """Sets the image_id of this NodeMapInner.

        ID of Image for that Node  # noqa: E501

        :param image_id: The image_id of this NodeMapInner.  # noqa: E501
        :type: str
        """

        self._image_id = image_id

    @property
    def instance_id(self):
        """Gets the instance_id of this NodeMapInner.  # noqa: E501

        ID of the instance for that Node (set by the server)  # noqa: E501

        :return: The instance_id of this NodeMapInner.  # noqa: E501
        :rtype: int
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this NodeMapInner.

        ID of the instance for that Node (set by the server)  # noqa: E501

        :param instance_id: The instance_id of this NodeMapInner.  # noqa: E501
        :type: int
        """

        self._instance_id = instance_id

    @property
    def node_id(self):
        """Gets the node_id of this NodeMapInner.  # noqa: E501

        ID of a Node  # noqa: E501

        :return: The node_id of this NodeMapInner.  # noqa: E501
        :rtype: int
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this NodeMapInner.

        ID of a Node  # noqa: E501

        :param node_id: The node_id of this NodeMapInner.  # noqa: E501
        :type: int
        """

        self._node_id = node_id

    @property
    def node_ip(self):
        """Gets the node_ip of this NodeMapInner.  # noqa: E501

        IP of a non-FPGA node (is used only if image_id=NON_FPGA)  # noqa: E501

        :return: The node_ip of this NodeMapInner.  # noqa: E501
        :rtype: str
        """
        return self._node_ip

    @node_ip.setter
    def node_ip(self, node_ip):
        """Sets the node_ip of this NodeMapInner.

        IP of a non-FPGA node (is used only if image_id=NON_FPGA)  # noqa: E501

        :param node_ip: The node_ip of this NodeMapInner.  # noqa: E501
        :type: str
        """

        self._node_ip = node_ip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodeMapInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeMapInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
