# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.instances_instance_id_body import InstancesInstanceIdBody  # noqa: E501
from swagger_client.rest import ApiException


class TestInstancesInstanceIdBody(unittest.TestCase):
    """InstancesInstanceIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstancesInstanceIdBody(self):
        """Test InstancesInstanceIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.instances_instance_id_body.InstancesInstanceIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
