# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.resource import Resource  # noqa: E501
from swagger_client.rest import ApiException


class TestResource(unittest.TestCase):
    """Resource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResource(self):
        """Test Resource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.resource.Resource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
