# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.instance_id_runlevel_body import InstanceIdRunlevelBody  # noqa: E501
from swagger_client.rest import ApiException


class TestInstanceIdRunlevelBody(unittest.TestCase):
    """InstanceIdRunlevelBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceIdRunlevelBody(self):
        """Test InstanceIdRunlevelBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.instance_id_runlevel_body.InstanceIdRunlevelBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
