# coding: utf-8

"""
    cloudFPGA Resource Manager API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.test_instance_instance_id_body import TestInstanceInstanceIdBody  # noqa: E501
from swagger_client.rest import ApiException


class TestTestInstanceInstanceIdBody(unittest.TestCase):
    """TestInstanceInstanceIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestInstanceInstanceIdBody(self):
        """Test TestInstanceInstanceIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.test_instance_instance_id_body.TestInstanceInstanceIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
